language: php
php:
 - '7.2'
 - '7.3'

before_script:
 - composer install --dev --no-interaction

script:
 - phpunit --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php tests

after_script:
  - php vendor/bin/coveralls -v