language: php
php:
 - '7.2'
 - '7.3'

env:
 - CODECOV_TOKEN="3723db4a-511e-40ff-bc99-c8da7d24207e"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-clover=coverage.xml --bootstrap vendor/autoload.php tests

after_success:
 - bash <(curl -s https://codecov.io/bash)